version: '3.4'

services:
  Onlineretailerwebapi:
    image: ${DOCKER_REGISTRY-}onlineretailerwebapi
    ports: 
    - "8100:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: OnlineRetailer.WebApi/Dockerfile
    depends_on:
      - seq

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml:ro

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093"
  


  seq:
    image: datalust/seq
    ports: 
        - "5341:5341"
        - "5342:80"
    volumes:
        - rps_seq_data1:/data
    environment:
        - ACCEPT_EULA=Y

  
volumes:
  rps_seq_data1: