global:
    scrape_interval: 10s


scrape_configs:

  - job_name: 'onlineretailerwebapi'
    static_configs:
    - targets: ['onlineretailerwebapi:80']

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']